name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Install dependencies
        run: |
          pipenv install --dev
      - name: Run tests
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          echo $PWD
          ls -la
          pipenv run pytest /lib/src/test

  merge:
    needs: [pytest, flake8]
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Merge pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automatic merge of ${{ github.event.pull_request.head.sha }} into ${{ github.event.pull_request.base.sha }}"
          delete-branch: true
          title: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          branch: ${{ github.event.pull_request.base.ref }}
          base: ${{ github.event.pull_request.base.ref }}
          head: ${{ github.head_ref }}